### ISSUE TITLE
Shift-arrow keys don't rotate a pattern anymore

### ISSUE THREAD

**Issue by AaronM04** [conwayste/conwayste#196]
**Describe the bug**
After selecting a pattern with the number keys (2 through 9 or 0), the pattern to draw on click is shown with some transparency. It used to be possible to rotate that pattern by holding down the Shift key and pressing the left or right arrow keys. Now, nothing happens.

**To Reproduce**
Check out the `am/issue190` branch, and run `cargo run --bin client`. Start a single player game. Type 2. Press shift-left repeatedly.
May also be reproducible with `master`. I haven't checked yet.

**Expected behavior**
The pattern to insert rotates by 90 degrees each time.

**Screenshots, video links, or pasted code**
Not yet.

**Your Environment:**
 - *Application:* client
 - *Conwayste version:* `conwayste 0.3.5`
 - *Rust version:* 1.50.0
 - *OS:* OpenBSD -CURRENT

**Comment by Manghi** [comment]
Good find @AaronM04! Confirmed to be broken on master as well. 

This broken during the refactor of game-area code from `client.rs` into `ui/gamearea.rs`. The pattern rotate code was mistakenly placed into the mouse handler instead of the key handler. 

PR has been opened under #197 to address the issue. Fix has been verified on my system.
